apiVersion: argoproj.io/v1alpha1

kind: Workflow

metadata:
  generateName: scargo-multi-step-with-cond-

spec:
  volumes:
    - name: workdir
      emptyDir: {}

  arguments:
    parameters:
      - name: input-val
      - name: input-type
      - name: s3-bucket
      - name: output-path

  entrypoint: main

  templates:
    - name: main
      steps:
        - - name: add-alpha
            template: exec-add-alpha
            arguments:
              parameters:
                - name: init-value
                  value: "{{workflow.parameters.input-val}}"
            when: "{{workflow.parameters.input-type}} == alpha"
          - name: add-beta
            template: exec-add-beta
            arguments:
              parameters:
                - name: init-value
                  value: "{{workflow.parameters.input-val}}"
            when: "{{workflow.parameters.input-type}} == beta"

    - name: exec-add-alpha
      inputs:
        parameters:
          - name: init-value
      outputs:
        artifacts:
          - name: txt-out
            path: /workdir/out
            archive:
              none: {}
            s3:
              endpoint: s3.amazonaws.com
              bucket: "{{workflow.parameters.s3-bucket}}"
              key: "{{workflow.parameters.output-path}}"
      initContainers:
        - name: mkdir
          image: alpine:latest
          command: ["mkdir", "-p", "/workdir/out"]
          mirrorVolumeMounts: true
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rwX", "/workdir"]
          mirrorVolumeMounts: true
      script:
        image: python:alpine
        command: [python]
        source: |
          result = str('{{inputs.parameters.init-value}}') + 'a'
          with open("{{outputs.artifacts.txt-out.path}}/add_alpha_{{inputs.parameters.init-value}}.txt", "w+") as fi:
              fi.write(result)

        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 30Mi
            cpu: 20m
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: exec-add-beta
      inputs:
        parameters:
          - name: init-value
      outputs:
        artifacts:
          - name: txt-out
            path: /workdir/out
            archive:
              none: {}
            s3:
              endpoint: s3.amazonaws.com
              bucket: "{{workflow.parameters.s3-bucket}}"
              key: "{{workflow.parameters.output-path}}"
      initContainers:
        - name: mkdir
          image: alpine:latest
          command: ["mkdir", "-p", "/workdir/out"]
          mirrorVolumeMounts: true
        - name: chmod
          image: alpine:latest
          command: ["chmod", "-R", "a+rwX", "/workdir"]
          mirrorVolumeMounts: true
      script:
        image: python:alpine
        command: [python]
        source: |
          result = str("{{inputs.parameters.init-value}}") + "b"
          with open("{{outputs.artifacts.txt-out.path}}/add_beta_{{inputs.parameters.init-value}}.txt", "w+") as fi:
              fi.write(result)

        resources:
          requests:
            memory: 30Mi
            cpu: 20m
          limits:
            memory: 30Mi
            cpu: 20m
        volumeMounts:
          - name: workdir
            mountPath: /workdir
