input-val: "1"
pre-word: "pre"
post-word: "post"
num-alphas: "3"

s3-bucket: pq-dataxfer-tmp
input-path: testing/scargo-examples
input-csv: add_numbers.csv
output-path: testing/scargo-examples/output
